version: '3'
services:
  web:
    image: webdevops/php-apache:8.1
    container_name: surtidor
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      - WEB_ALIAS_DOMAIN=laravel-webserver
      - WEB_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - laravel_networñk
  db:
    image: postgres:13
    container_name: surtidor-db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=surtidor-db
      - POSTGRES_USER=postgre
      - POSTGRES_PASSWORD=123
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - laravel_network
  composer:
    image: composer:2.0
    container_name: laravel-composer
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - web

networks:
  laravel_network:
    driver: bridge
